# revision 29349
# category Package
# catalog-ctan /graphics/metapost/contrib/macros/dviincl
# catalog-date 2012-04-10 15:00:16 +0200
# catalog-license pd
# catalog-version 1.00
Name:		texlive-dviincl
Version:	1.00
Release:	11
Summary:	Include a DVI page into MetaPost output
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/graphics/metapost/contrib/macros/dviincl
License:	PD
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/dviincl.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/dviincl.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea

%description
DVItoMP is one of the auxiliary programs available to any
MetaPost package; it converts a DVI file into a MetaPost file.
Using it, one can envisage including a DVI page into an EPS
files generated by MetaPost. Such files allow pages to include
other pages.

%post
    %{_sbindir}/texlive.post

%postun
    if [ $1 -eq 0 ]; then
	%{_sbindir}/texlive.post
    fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/metapost/dviincl/fix_brks.mp
%{_texmfdistdir}/metapost/dviincl/fix_page.mp
%doc %{_texmfdistdir}/doc/metapost/dviincl/0czytaj.sla
%doc %{_texmfdistdir}/doc/metapost/dviincl/0dviincl.inf
%doc %{_texmfdistdir}/doc/metapost/dviincl/README
%doc %{_texmfdistdir}/doc/metapost/dviincl/README.pl
%doc %{_texmfdistdir}/doc/metapost/dviincl/storyx.tex
%doc %{_texmfdistdir}/doc/metapost/dviincl/test-bop.mp
%doc %{_texmfdistdir}/doc/metapost/dviincl/test-bop.tex
%doc %{_texmfdistdir}/doc/metapost/dviincl/testit.bat
%doc %{_texmfdistdir}/doc/metapost/dviincl/testit.sh

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar metapost doc %{buildroot}%{_texmfdistdir}
