%global tl_name dviincl
%global tl_revision 29349

Name:		texlive-%{tl_name}
Epoch:		1
Version:	1.00
Release:	%{tl_revision}.1
Summary:	Include a DVI page into MetaPost output
Group:		Publishing
URL:		https://www.ctan.org/tex-archive/graphics/metapost/contrib/macros/dviincl
License:	pd
Source0:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/dviincl.r%{tl_revision}.tar.xz
Source1:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/dviincl.doc.r%{tl_revision}.tar.xz
BuildArch:	noarch
BuildSystem:	texlive
BuildRequires:	texlive-tlpkg
%texlive_base_requires
Provides:	texlive(%{tl_name}) = %{tl_revision}

%description
DVItoMP is one of the auxiliary programs available to any MetaPost
package; it converts a DVI file into a MetaPost file. Using it, one can
envisage including a DVI page into an EPS files generated by MetaPost.
Such files allow pages to include other pages.

