Name:		texlive-dviincl
Version:	1.00
Release:	1
Summary:	Include a DVI page into MetaPost output
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/graphics/metapost/contrib/macros/dviincl
License:	PD
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/dviincl.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/dviincl.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(post):	texlive-tlpkg
Conflicts:	texlive-texmf <= 20110705-3
Conflicts:	texlive-doc <= 20110705-3

%description
One of the auxiliary programs belonging to every MetaPost
package is DVItoMP, converting a DVI into a MetaPost file.
Hence the idea of including a DVI page into the EPS files
generated by MetaPost. An MPX file produced by DVItoMP is then
processed by MetaPost with an axiliary file.

%pre
    %_texmf_mktexlsr_pre

%post
    %_texmf_mktexlsr_post

%preun
    if [ $1 -eq 0 ]; then
	%_texmf_mktexlsr_pre
    fi

%postun
    if [ $1 -eq 0 ]; then
	%_texmf_mktexlsr_post
    fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/metapost/dviincl/fix_brks.mp
%{_texmfdistdir}/metapost/dviincl/fix_page.mp
%doc %{_texmfdistdir}/doc/metapost/dviincl/0czytaj.sla
%doc %{_texmfdistdir}/doc/metapost/dviincl/0dviincl.inf
%doc %{_texmfdistdir}/doc/metapost/dviincl/README
%doc %{_texmfdistdir}/doc/metapost/dviincl/README.pl
%doc %{_texmfdistdir}/doc/metapost/dviincl/storyx.tex
%doc %{_texmfdistdir}/doc/metapost/dviincl/test-bop.mp
%doc %{_texmfdistdir}/doc/metapost/dviincl/test-bop.tex
%doc %{_texmfdistdir}/doc/metapost/dviincl/testit.bat
%doc %{_texmfdistdir}/doc/metapost/dviincl/testit.sh

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar metapost doc %{buildroot}%{_texmfdistdir}
